global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: 'YOUR_BOT_TOKEN'
        chat_id: -4700416302
        parse_mode: 'HTML'
        message: |
          <b>Alert: {{ .GroupLabels.alertname }}</b>
          <b>Status: {{ .Status }}</b>
          <b>Severity: {{ .CommonLabels.severity }}</b>
          <b>Description:</b> {{ .CommonAnnotations.description }} 