version: '3'

services:
  ai-business-fire-service:
    container_name: fire-biz-sv
    image: qvision-ai-fire-business-service
    restart: always
    networks:
      - fire
    volumes:
      - /ai-business-service:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: python server.py

  ai-objects-fire-service:
    container_name: fire-obj-sv
    image: qvision-ai-fire-service
    build: ../ai-objects-service
    restart: always
    networks:
      - fire
    volumes:
      - /ai-objects-service:/app
      - /fire_detection:/fire_detection
      - /data/parking:/app/assets/video
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: python server.py


  ai-visualize-fire-service:
    container_name: fire-vs-sv
    image: qvision-ai-fire-visualize-service
    restart: always
    networks:
      - fire
    volumes:
      - /ai-visualize-service:/app
    ports:
      - "6969:6969"
    # depends_on:
    #   - ai-business-service
    #   - ai-objects-service
    command: gunicorn -w 4 -b 0.0.0.0:6969 wsgi:app


  ai-fire-tranship-service:
    container_name: ai-fire-tranship-service
    image: redis
    restart: always
    ports:
      - "63796:6379"
    networks:
      - fire

networks:
  fire:
    name: fire
    external: true
